name: omni_jitsi_meet_web_plugin
description: Jitsi Meet Web Plugin. A plugin for integrating open source Jitsi Meet API in flutter.
version: 1.0.15
homepage: https://github.com/thorito/jitsi_meet

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.24.1'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  omni_jitsi_meet_platform_interface: ^1.0.15

  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: JitsiMeetPlugin
        fileName: jitsi_meet_web.dart
