group 'com.thorito.jitsi_meet'
version '1.0.0'

buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        maven { url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases" }
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterCompileSdkVersion = '36'
def flutterTargetSdkVersion = '36'

def flutterMinSdkVersion = localProperties.getProperty('flutter.minSdkVersion')
if (flutterMinSdkVersion == null) {
    flutterMinSdkVersion = '26'
}

def flutterNdkVersion = localProperties.getProperty('flutter.ndkVersion')
if (flutterNdkVersion == null) {
    flutterNdkVersion = '29.0.14206865'
}

def versionBuildTools = localProperties.getProperty('flutter.versionBuildTools')
if (versionBuildTools == null) {
    versionBuildTools = '36.1.0'
}



android {
    namespace 'com.thorito.jitsi_meet'
    compileSdkVersion flutterCompileSdkVersion.toInteger()
    buildToolsVersion versionBuildTools
    ndkVersion flutterNdkVersion

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion flutterMinSdkVersion.toInteger()
        targetSdkVersion flutterTargetSdkVersion.toInteger()
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // Jitsi Meet from https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/org/jitsi/react/jitsi-meet-sdk
    // implementation ('org.jitsi.react:jitsi-meet-sdk:10.2.1') { transitive = true }
    implementation ('org.jitsi.react:jitsi-meet-sdk:12.0.0') { transitive = true }
}
